@baseUrl=http://localhost:3000
@createdHostId = {{createHost.response.body.$.id}}

### Create Usuer

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "beto",
  "password": "123",
  "active": true,
  "lastLogin": "-",
  "AccessToken": "",
  "privilege": 1
}

### Get(post) user by User

# @name getUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "beto",
  "password": ""
}

### Create Olt

# @name createHost
POST {{baseUrl}}/olts
Content-Type: application/json

{
  "status": false,
  "OltName": "OltC",
  "Armario": "POP MatrizB",
  "PowerdB": "",
  "maxClients": "256",
  "ipAddress": "127.0.0.3",
  "lastUpdate": ""
}


### Create Slots
# @name createSlots
POST {{baseUrl}}/slots
Content-Type: application/json

{
  "status": 1,
  "slot": "0/18",
  "BoardName": "",
  "OnuDiscovery": 0,
  "OnuProvisioned": 10,
  "OnuOnline": 10,
  "lastUpdate": "",
  "oltId": 2
}
### Show All Slots

# @name viewAllSlots
GET {{baseUrl}}/users/

### Get Slot ByID
GET {{baseUrl}}/olts

### Get All Users
GET {{baseUrl}}/users

### Get User ByID
GET {{baseUrl}}/users/7

### Update a host

PUT {{baseUrl}}/users/16
Content-Type: application/json

{
  "lastLogin": "08/01/2024 10:00:00"
}

### Update a olt

PUT {{baseUrl}}/olts/2
Content-Type: application/json

{
  "status": true
}

### Delete a host

DELETE {{baseUrl}}/users/1