@baseUrl=http://localhost:3000
@createdHostId = {{createHost.response.body.$.id}}

### Create Usuer

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "michael",
  "password": "notex021",
  "active": true,
  "lastLogin": "-",
  "privilege": 1
}

### Get(post) user by User

# @name getUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "beto",
  "password": "123"
}

### Create Olt

# @name createHost
POST {{baseUrl}}/olts
Content-Type: application/json

{
  "status": false,
  "OltName": "OltDC",
  "Armario": "POP MatrizD5",
  "PowerdB": "",
  "maxClients": "",
  "ipAddress": "50.50.50.50"
}


### Create Slots
# @name createSlots
POST {{baseUrl}}/slots
Content-Type: application/json

{
  "status": 1,
  "slot": "0/3",
  "OnuDiscovery": 80,
  "OnuProvisioned": 40,
  "OnuOnline": 24,
  "oltId": 3
}
### Show All Slots

# @name viewAllSlots
GET {{baseUrl}}/users/

### Get Slot ByID
GET {{baseUrl}}/olts

### Get All Users
GET {{baseUrl}}/users

### Get User ByID
GET {{baseUrl}}/users/7

### Update a host

PUT {{baseUrl}}/users/16
Content-Type: application/json

{
  "lastLogin": "08/01/2024 10:00:00"
}

### Delete a host

DELETE {{baseUrl}}/users/1